### PR TITLE
Use tuplez.Composition instead of our Tupler. Fixes #12

### LINKED ISSUE #12: Tuple 4 supported?
I can't get this to compile.
```
  val claimQueryParams: QueryParameters[(Option[List[String]], Option[List[String]], Option[String], Option[String]), DummyError] = 
     (
        listParam[String]("lossParts").? & 
        listParam[String]("granularity").? & 
        param[String]("startDate").? & 
        param[String]("endDate").?
     )
```
If I remove the last parameter, (and alter the signature), then it seems to work well... here's the compile error.

```
[info] compiling 1 Scala source to C:\temp\ilsclaims\out\frontend\compile.dest\classes ...
[warn] Flag -Xsemanticdb set repeatedly
[error] -- [E007] Type Mismatch Error: C:\temp\ilsclaims\frontend\src\routes.scala:124:8
[error] 124 |        listParam[String]("lossParts").? &
[error]     |        ^
[error]     |Found:    urldsl.language.QueryParameters[?1.Out, urldsl.errors.DummyError]
[error]     |Required: urldsl.language.QueryParameters[(Option[List[String]], Option[List[String]],
[error]     |
[error]     |  Option[String]
[error]     |
[error]     |, Option[String]), urldsl.errors.DummyError]
[error]     |
[error]     |where:    ?1 is an unknown value of type urldsl.language.Tupler.Aux[(Option[List[String]], Option[List[String]],
[error]     |  Option[String]
[error]     |), Option[String], ((Option[List[String]], Option[List[String]], Option[String])
[error]     |  ,
[error]     |Option[String])]
[error] 125 |        listParam[String]("granularity").? &
[error] 126 |        param[String]("startDate").? &
[error] 127 |        param[String]("endDate").?
[error]     |
[error]     | longer explanation available when compiling with `-explain`
```
I think I did manage to get it to compile, essentially by poking around with the tuples... 

```

  val claimQueryParams: QueryParameters[((Option[List[String]], Option[List[String]], Option[String]), Option[String]), DummyError] = 
     (
      (
        listParam[String]("lossParts").? &         
        listParam[String]("granularity").? &
        param[String]("startDate").?
        ) &
        param[String]("endDate").?
     )
     
```
But it's a bit of an odd construct, and the route ends up looking; 
```
decode = args => Page.ClaimReport(args.path, args.params._1._1, args.params._1._2, args.params._1._3, args.params._2),
```
:-D

I'm not sure if that would be expected?

Edir: This appears to throw a runtime error... so perhaps my trick is not so good!

### PR DESCRIPTION
**Pull request by raquo**
All existing tests passed as-is, however in more complex cases tuple flattening is more aggressive now. I've added some tests to exercise more tupled methods.

See also my comments in #12 regarding the naming of `unapply`.

### CODE REVIEW

File: url-dsl/src/test/scala/urldsl/language/PathWithQueryParametersSpec.scala [hunk 1]
```diff
@@ -23,11 +27,17 @@ class PathWithQueryParametersSpec extends AnyFlatSpec with Matchers {
...
-      "http://localhost:8080/hello/2019/january?age=10&drinks=orange%20juice&drinks=water"
+      sampleUrl
     ) should be(
       Right(UrlMatching((2019, "january"), (10, List("orange juice", "water"))))
     )
 
+    (pathWithParams & param[(Int, Int)]("tuple")).matchRawUrl(
+      sampleUrl
+    ) should be(
+      Right(UrlMatching((2019, "january"), (10, List("orange juice", "water"), 44, 55)))
```
Comment (raquo) [inline url-dsl/src/test/scala/urldsl/language/PathWithQueryParametersSpec.scala:38]: As an example, with the old Tupler, this evaluated to the following:

`UrlMatching((2019, "january"), ((10, List("orange juice", "water")), (44, 55)))`

instead of the new and flatter:

`UrlMatching((2019, "january"), (10, List("orange juice", "water"), 44, 55))`

I think the new behaviour is good? Or at least, not bad.

Comment (sherpal) [reply url-dsl/src/test/scala/urldsl/language/PathWithQueryParametersSpec.scala:38]: I think it is much better indeed. In the example above, if someone thinks that `(10, List("orange juice", "water"))` has meaning in itself, they should map it to a case class before tupling :+1:

**Comment by sherpal** [comment]
Thanks for this and for the comprehensive tests! I think it is a very nice addition/transformation.
